name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Make test application_yml
    - name: Make test application_yml
      env:
        APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
      run: |
        mkdir -p ./src/test/resources && cd "$_"
        touch ./application.properties
        echo $APPLICATION_PROPERTIES | base64 --decode > application.properties
      shell: bash

    # Cache Gradle dependencies to improve performance
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Set up Gradle (only if wrapper is not present)
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.11.1'

    # Build with Gradle Wrapper
    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generate and submit dependency graph
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
